In [25]:
from scipy.spatial.transform import Rotation as R
import warnings
import math
from utils2 import R3_so3, so3_R3
from scipy.linalg import expm, logm
import numpy as np
from icecream import ic

In [26]:
Rot_des = R.from_euler('z', -20, degrees=True).as_matrix()
Rot_des_neg = R.from_euler('z', 340, degrees=True).as_matrix()

In [29]:
ic(R.from_matrix(Rot_des).as_euler('zxy', degrees=True))
ic(R.from_matrix(Rot_des_neg).as_euler('zxy', degrees=True))
ic(Rot_des)
ic(Rot_des_neg)

ic| R.from_matrix(Rot_des).as_euler('zxy', degrees=True): array([20.,  0.,  0.])
ic| R.from_matrix(Rot_des_neg).as_euler('zxy', degrees=True): array([-20.,   0.,   0.])
ic| Rot_des: array([[ 0.93969262, -0.34202014,  0.        ],
                    [ 0.34202014,  0.93969262,  0.        ],
                    [ 0.        ,  0.        ,  1.        ]])
ic| Rot_des_neg: array([[ 0.93969262,  0.34202014,  0.        ],
                        [-0.34202014,  0.93969262,  0.        ],
                        [ 0.        ,  0.        ,  1.        ]])


array([[ 0.93969262,  0.34202014,  0.        ],
       [-0.34202014,  0.93969262,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [11]:
w_z = logm(Rot_des)
w_z = so3_R3(w_z*0.01)
w_z

array([0.        , 0.        , 0.02094395])

In [12]:
w_z_neg = logm(Rot_des_neg)

w_z_neg = so3_R3(w_z_neg)
w_z_neg

array([ 0.       ,  0.       , -2.0943951])

In [14]:
R_1 = R.from_euler('z', 10, degrees=True).as_matrix()
R_2 = R.from_euler('z', 20, degrees=True).as_matrix()
R_diff = np.dot(R_1.T, R_2)
w_diff = logm(R_diff)
ic(w_diff)
w_diff = so3_R3(w_diff)
w_diff
np.rad2deg(w_diff[2])
phi_des = np.rad2deg(0.5)
ic(phi_des)

ic| w_diff: array([[-1.20396595e-16, -1.74532925e-01,  0.00000000e+00],
                   [ 1.74532925e-01,  4.69853565e-17,  0.00000000e+00],
                   [ 0.00000000e+00,  0.00000000e+00, -1.11022302e-16]])
ic| phi_des: 28.64788975654116

28.64788975654116

In [24]:
Rot_des.T@Rot_des_neg   
R.from_matrix(Rot_des.T@Rot_des_neg).as_euler('zyx', degrees=True)

array([-120.,    0.,   -0.])